#!/usr/bin/env bash

function main {
  local shome="${_linkerd_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -x "$(which linkerd 2>&- || true)" ]]; then
    if [[ -x "$(which namerd 2>&- || true)" ]]; then
      return 0
    fi
  fi

  return 1
}

source sub "$BASH_SOURCE" "$@"
