#!/usr/bin/env bash

function main {
  local shome="${_linkerd_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -f "$shome/vendor/linkerd-0.6.0-exec" ]]; then
    if [[ -f "$shome/vendor/namerd-0.6.0-exec" ]]; then
      return 0
    fi
  fi

  return 1
}

source sub "$BASH_SOURCE" "$@"
