#!/usr/bin/env bash

function _linkerd_profile {
  local shome="${_linkerd_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  LINKERD_VERSION='1.1.3'
}

_linkerd_profile
