#!/usr/bin/env bash

function server {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome/vendor/linkerd"
  exec linkerd "config/linkerd.yaml"
}

server "$@"
