#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -f "$shome/vendor/linkerd/linkerd-0.4.0-exec" ]]; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
